### ISSUE TITLE
unable to run that application

### ISSUE THREAD

**Issue by Diptiranjanjena** [tradestation/sample-webapi-console-csharp#1]
error msg

An unhandled exception of type 'System.ArgumentException' occurred in System.dll

Additional information: Only Uri prefixes starting with 'http://' or 'https://' are supported.

 listener.Prefixes.Add(this.RedirectUri);(//Giving eror here)

**Comment by johnjelinek** [comment]
What did you set your `App.config`'s [RedirectUri](https://github.com/tradestation/sample-webapi-console-csharp/blob/master/sample-webapi-console-csharp/App.config#L17) to?

**Comment by Diptiranjanjena** [comment]
i did not find what url i will provide  there please let me know the url and key for this

**Comment by johnjelinek** [comment]
Try the pre-populated url. If you don't have a key, you can sign up for one
at https://developer.tradestation.com.

**Comment by GBULLR** [comment]
Tradestation appears to not be giving out new keys which makes this impossible. And I am a customer.
