### ISSUE TITLE
POST methods not functioning.

### ISSUE THREAD

**Issue by BenSanex** [tradestation/sample-webapi-console-csharp#2]
Hi, wondering if this code is still valid. I'm attempting to run this against the SIM environment and get 400 errors on the GetConfirmations and PlaceOrder methods with no error details. Looking at the v2 specs it seems the serialized order is supposed to be sent in the query string instead of part of the request body? I tried that and it went worse so just looking for some direction.

**Comment by BenSanex** [comment]
Reconfigured using a different http library and got the right error. Never mind!

**Comment by lancehunt** [comment]
Glad you got it working. Some of these samples have not been updated in years so YMMV.

In 2017 we dropped support for TLS 1.0 which is the default for .NET.

**Comment by BenSanex** [comment]
I got it converted to dotnet core and switched to RestSharp for the API requests so it wasn't eating my errors anymore and now its smooth sailing. They're old but they still work!
